void readInputFile(char *filename);
void initScanner(char *filename1, char *filename2);
void scanner();
void lexScan();
void isNumber();
void isAlpha();
void isOther();
void output(int n);
void isAnotation();

enum TK
{
    IDENFR,
    INTCON,
    STRCON,
    MAINTK,
    CONSTTK,
    INTTK,
    BREAKTK,
    CONTINUETK,
    IFTK,
    ELSETK,
    NOT,
    AND,
    OR,
    WHILETK,
    GETINTTK,
    PRINTFTK,
    RETURNTK,
    PLUS,
    MINU,
    VOIDTK,
    MULT,
    DIV,
    MOD,
    LSS,
    LEQ,
    GRE,
    GEQ,
    EQL,
    NEQ,
    ASSIGN,
    SEMICN,
    COMMA,
    LPARENT,
    RPARENT,
    LBRACK,
    RBRACK,
    LBRACE,
    RBRACE,
    ERROR,
    ANOTATION,
    EndOfFile
};

char Index[][20] = {"Ident",
                    "IntConst",
                    "FormatString",
                    "main",
                    "const",
                    "int",
                    "break",
                    "continue",
                    "if",
                    "else",
                    "!",
                    "&&",
                    "||",
                    "while",
                    "getint",
                    "printf",
                    "return",
                    "+",
                    "-",
                    "void",
                    "*",
                    "/",
                    "%",
                    "<",
                    "<=",
                    ">",
                    ">=",
                    "==",
                    "!=",
                    "=",
                    ";",
                    ",",
                    "(",
                    ")",
                    "[",
                    "]",
                    "{",
                    "}",
                    "",
                    ""};

char printTK[][20] = {"IDENFR",
                      "INTCON",
                      "STRCON",
                      "MAINTK",
                      "CONSTTK",
                      "INTTK",
                      "BREAKTK",
                      "CONTINUETK",
                      "IFTK",
                      "ELSETK",
                      "NOT",
                      "AND",
                      "OR",
                      "WHILETK",
                      "GETINTTK",
                      "PRINTFTK",
                      "RETURNTK",
                      "PLUS",
                      "MINU",
                      "VOIDTK",
                      "MULT",
                      "DIV",
                      "MOD",
                      "LSS",
                      "LEQ",
                      "GRE",
                      "GEQ",
                      "EQL",
                      "NEQ",
                      "ASSIGN",
                      "SEMICN",
                      "COMMA",
                      "LPARENT",
                      "RPARENT",
                      "LBRACK",
                      "RBRACK",
                      "LBRACE",
                      "RBRACE",
                      "ERROR",
                      ""};